language: node_js
node_js:
  - 14
services:
  - docker

before_script:
  - docker image pull dhawton/nodejs:latest
  - npm install -g yarn

test:
  - yarn lint

script:
  - yarn
  - yarn build
  - if [[ "$TRAVIS_TAG" != "" ]] || [[ "$TRAVIS_BRANCH" == "dev" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]]; then
    docker build -t flyakorg/wobanapi:latest
    fi

after_script:
  - if [ "$TRAVIS_TAG" != "" ];
    then docker tag flyakorg/api flyakorg/api:latest;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push flyakorg/api:latest;
    docker tag flyakorg/api:latest flyakorg/api:$TRAVIS_TAG;
    docker push flyakorg/api:$TRAVIS_TAG;
    fi
  - if [ "$TRAVIS_BRANCH" == "dev" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker tag flyakorg/api flyakorg/api:devel;
    docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
    docker push flyakorg/api:devel;
    fi

after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL